### ISSUE TITLE
Write access to wiki

### ISSUE THREAD

**Issue by mtorpey** [StAResComp/2018-12-10-standrews#2]
Hi folks!  I'd like to add my sticky note feedback to the wiki, but I don't have access.  Could someone add me? :) @alex-konovalov @pgmccann

**Comment by olexandr-konovalov** [comment]
I have write access to the repo but no admin rights. You need to wait until @pgmccann will see this.

**Comment by olexandr-konovalov** [comment]
I made a page https://github.com/StAResComp/2018-12-10-standrews/wiki/Feedback-from-sticky-notes and started to put the feedback from my stickies.
